//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Payments_Tab
    {
        public int ID { get; set; }
        public string Customer_Id { get; set; }
        public string Invoice_No { get; set; }
        public string Amount_Paid { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
    }
}
