//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Order_Line
    {
        public string Order_No { get; set; }
        public int Line_No { get; set; }
        public string Barcode { get; set; }
        public string Code_Name { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> ProfitMargin { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
        public string Prod_Group { get; set; }
        public string BundleSize { get; set; }
    }
}
