//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Order_Tab
    {
        public int Order_No { get; set; }
        public string Supplier { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<decimal> TotalBillAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string Status { get; set; }
    }
}
