//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ret_Product_Tab
    {
        public Nullable<int> Prod_Num { get; set; }
        public string ProductCode { get; set; }
        public string Name { get; set; }
        public string UnitCost { get; set; }
        public string ProfitMargin { get; set; }
        public string SalesPrice { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ProductGroup { get; set; }
        public string QTY { get; set; }
        public string ScanCode { get; set; }
        public string Supplier { get; set; }
        public string Line_no { get; set; }
        public string created_by { get; set; }
        public string Purchase_qty { get; set; }
        public string BundleSize { get; set; }
        public Nullable<long> NewProductID { get; set; }
        public Nullable<int> CleanProductCode { get; set; }
    }
}
