//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ret_Invoice_tab
    {
        public int Inv_Id { get; set; }
        public string Customer { get; set; }
        public Nullable<System.DateTime> Inv_date { get; set; }
        public string total_item_discount { get; set; }
        public string total_qty { get; set; }
        public string total_price { get; set; }
        public string user_id { get; set; }
        public string status { get; set; }
        public string paid_amount_cash { get; set; }
    }
}
