//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSaleCartDetail
    {
        public int SaleCartDetailID { get; set; }
        public string ProductID { get; set; }
        public int SaleQuantity { get; set; }
        public double SaleUnitPrice { get; set; }
        public int CompanyID { get; set; }
        public int BranchID { get; set; }
        public int UserID { get; set; }
    
        public virtual tblStock tblStock { get; set; }
    }
}
